# Site settings
title: CMD+U Conference
email: hello@cmdnouconf.com
description: iOS conference about testing in Barcelona 8th July!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmdnouconf.com" # the base hostname & protocol for your site
twitter_username: cmdnouconf
github_username: cmdnouconf

# Build settings
markdown: kramdown
permalink: none
highlighter: rouge
timezone: Europe/Madrid
encoding: utf-8
paginate_path: "blog/page:num"

#external urls
lyst_web: http://lyst.com
